#include "Reading.h"
#include <map>

struct CardAssociations {
	BString astrological;
	BString hebrewLetter;
	BString meaning;
	BString element;
	BString color;
	BString incense;
	BString keywords;
};

static std::map<BString, CardAssociations> cardData = {
	{"1 The Magician",
		{"Mercury", "Beth",
			"Represents the conscious mind, the intellect, and the power of manifestation.", "Air",
			"Yellow and Red", "Lavender", "Will, Skill, Action"}},
	{"2 The High Priestess",
		{"Moon", "Gimel", "Represents the subconscious mind, intuition, and hidden knowledge.",
			"Water", "Silver and White", "Myrrh", "Intuition, Mystery, Silence"}},
	{"3 The Empress",
		{"Venus", "Daleth", "Represents motherhood, fertility, and the abundance of nature.",
			"Earth", "Green and Blue", "Rose", "Abundance, Fertility, Nature"}},
	{"4 The Emperor",
		{"Aries", "Heh", "Represents fatherhood, authority, and the structure of society.", "Fire",
			"Red and Gold", "Sandalwood", "Authority, Stability, Leadership"}},
	{"5 The Hierophant",
		{"Taurus", "Vav", "Represents tradition, religion, and the pursuit of knowledge.", "Earth",
			"Blue and Green", "Lavender", "Tradition, Education, Guidance"}},
	{"6 The Lovers",
		{"Gemini", "Zain", "Represents relationships, choices, and the union of opposites.", "Air",
			"Blue and Yellow", "Jasmine", "Choice, Partnership, Harmony"}},
	{"7 The Chariot",
		{"Cancer", "Cheth", "Represents victory, willpower, and the mastery of opposing forces.",
			"Water", "Blue and Red", "Peppermint", "Victory, Control, Willpower"}},
	{"8 Strength",
		{"Leo", "Teth",
			"Represents courage, passion, and the integration of the conscious and subconscious "
			"minds.",
			"Fire", "Orange and Purple", "Cinnamon", "Courage, Patience, Strength"}},
	{"9 The Hermit",
		{"Virgo", "Yod", "Represents introspection, solitude, and the search for inner wisdom.",
			"Earth", "Yellow and Gray", "Cypress", "Introspection, Solitude, Wisdom"}},
	{"10 Wheel Of Fortune",
		{"Jupiter", "Kaph", "Represents cycles, destiny, and the ever-changing nature of life.",
			"Fire", "Purple and Blue", "Spikenard", "Change, Destiny, Fortune"}},
	{"11 Justice",
		{"Libra", "Lamed", "Represents fairness, balance, and the consequences of one's actions.",
			"Air", "Blue and White", "Frankincense", "Fairness, Balance, Law"}},
	{"12 The Hanged Man",
		{"Neptune", "Mem", "Represents sacrifice, surrender, and a change in perspective.", "Water",
			"Teal and Brown", "Copal", "Suspension, Sacrifice, Perspective"}},
	{"13 Death",
		{"Scorpio", "Nun", "Represents transformation, endings, and new beginnings.", "Water",
			"Black and Maroon", "Patchouli", "Transformation, Ending, Beginning"}},
	{"14 Temperance",
		{"Sagittarius", "Samekh", "Represents balance, harmony, and the integration of opposites.",
			"Fire", "Orange and Indigo", "Benzoin", "Balance, Moderation, Patience"}},
	{"15 The Devil",
		{"Capricorn", "Ayin",
			"Represents materialism, addiction, and the darker aspects of human nature.", "Earth",
			"Gray and Black", "Asafoetida", "Bondage, Addiction, Materialism"}},
	{"16 The Tower",
		{"Mars", "Peh",
			"Represents sudden change, upheaval, and the destruction of old structures.", "Fire",
			"Red and Black", "Turpentine", "Disaster, Upheaval, Liberation"}},
	{"17 The Star",
		{"Aquarius", "Tzaddi", "Represents hope, inspiration, and the connection to the divine.",
			"Air", "Blue and White", "Star Anise", "Hope, Inspiration, Serenity"}},
	{"18 The Moon",
		{"Pisces", "Qoph", "Represents intuition, dreams, and the exploration of the subconscious.",
			"Water", "Indigo and Violet", "Night-Blooming Jasmine", "Illusion, Fear, Intuition"}},
	{"19 The Sun",
		{"Sun", "Resh", "Represents joy, vitality, and the celebration of life.", "Fire",
			"Yellow and Gold", "Sunflower", "Joy, Success, Vitality"}},
	{"20 Judgement",
		{"Pluto", "Shin", "Represents resurrection, forgiveness, and the final judgment.", "Water",
			"Red and White", "Sweetgrass", "Rebirth, Absolution, Renewal"}},
	{"21 The World",
		{"Saturn", "Tav",
			"Represents completion, fulfillment, and the integration of all aspects of the self.",
			"Earth", "Green and Blue", "Cedar", "Completion, Integration, Achievement"}},
	{"Ace Of Cups",
		{"Water", "Heh",
			"Represents the beginning of a new emotional cycle, the potential for love and "
			"happiness.",
			"Water", "White and Blue", "Rose", "Emotion, Intuition, Love"}},
	{"Two Of Cups",
		{"Venus in Cancer", "Cheth",
			"Represents a deep connection between two people, a partnership based on love and "
			"mutual respect.",
			"Water", "Red and Pink", "Rose", "Partnership, Attraction, Union"}},
	{"Three Of Cups",
		{"Mercury in Cancer", "Cheth",
			"Represents a celebration of friendship, a time of joy and shared happiness.", "Water",
			"Yellow and Blue", "Vanilla", "Celebration, Friendship, Joy"}},
	{"Four Of Cups",
		{"Moon in Cancer", "Cheth",
			"Represents a time of emotional withdrawal, a need to re-evaluate one's feelings.",
			"Water", "Blue and Gray", "Myrrh", "Apathy, Contemplation, Disappointment"}},
	{"Five Of Cups",
		{"Mars in Scorpio", "Nun",
			"Represents a sense of loss and disappointment, a need to grieve and move on.", "Water",
			"Black and Red", "Patchouli", "Loss, Regret, Grief"}},
	{"Six Of Cups",
		{"Sun in Scorpio", "Nun",
			"Represents a return to the past, a time of nostalgia and happy memories.", "Water",
			"Orange and Blue", "Nostalgia", "Nostalgia, Innocence, Memories"}},
	{"Seven Of Cups",
		{"Venus in Scorpio", "Nun",
			"Represents a time of wishful thinking, a need to make a choice and take action.",
			"Water", "Purple and Blue", "Lavender", "Choices, Illusions, Imagination"}},
	{"Eight Of Cups",
		{"Saturn in Pisces", "Qoph",
			"Represents a time of emotional transition, a need to move on from the past.", "Water",
			"Gray and Blue", "Hyssop", "Abandonment, Withdrawal, Search"}},
	{"Nine Of Cups",
		{"Jupiter in Pisces", "Qoph",
			"Represents a time of emotional fulfillment, a wish come true.", "Water",
			"Purple and Crimson", "Amaretto", "Satisfaction, Luxury, Wishes"}},
	{"Ten Of Cups",
		{"Mars in Pisces", "Qoph",
			"Represents a time of lasting happiness, a deep sense of emotional security.", "Water",
			"Blue and Red", "Champagne", "Happiness, Harmony, Blessings"}},
	{"Page Of Cups",
		{"Earth of Water", "Heh", "Represents a message of love, a new emotional beginning.",
			"Water", "Blue and Turquoise", "Jasmine", "Messages, Intuition, Invitation"}},
	{"Knight Of Cups",
		{"Air of Water", "Heh", "Represents a romantic proposal, a journey of the heart.", "Water",
			"Blue and Green", "Rose", "Romance, Adventure, Invitation"}},
	{"Queen Of Cups",
		{"Water of Water", "Heh",
			"Represents a compassionate and intuitive woman, a loving mother and wife.", "Water",
			"Blue and Silver", "Lily of the Valley", "Compassion, Calm, Nurture"}},
	{"King Of Cups",
		{"Fire of Water", "Heh",
			"Represents a mature and emotionally balanced man, a wise and compassionate leader.",
			"Water", "Blue and Purple", "Sandalwood", "Emotional Balance, Diplomacy, Control"}},
	{"Ace Of Pentacles",
		{"Earth", "Heh",
			"Represents the beginning of a new financial cycle, the potential for prosperity and "
			"abundance.",
			"Earth", "Green and Brown", "Patchouli", "Prosperity, Opportunity, Manifestation"}},
	{"Two Of Pentacles",
		{"Jupiter in Capricorn", "Ayin",
			"Represents a time of financial juggling, a need to balance competing priorities.",
			"Earth", "Red and Blue", "Clove", "Balance, Priorities, Adaptation"}},
	{"Three Of Pentacles",
		{"Mars in Capricorn", "Ayin",
			"Represents a time of collaboration and teamwork, a successful project.", "Earth",
			"Yellow and Green", "Frankincense", "Teamwork, Collaboration, Skill"}},
	{"Four Of Pentacles",
		{"Sun in Capricorn", "Ayin",
			"Represents a time of financial security, a need to hold on to what one has.", "Earth",
			"Brown and Green", "Cedar", "Security, Possession, Greed"}},
	{"Five Of Pentacles",
		{"Mercury in Taurus", "Vav",
			"Represents a time of financial hardship, a need to seek help from others.", "Earth",
			"Gray and Blue", "Myrrh", "Hardship, Poverty, Illness"}},
	{"Six Of Pentacles",
		{"Moon in Taurus", "Vav",
			"Represents a time of generosity and charity, a need to share one's wealth.", "Earth",
			"Purple and Green", "Cinnamon", "Generosity, Sharing, Reciprocity"}},
	{"Seven Of Pentacles",
		{"Saturn in Taurus", "Vav",
			"Represents a time of patience and perseverance, a need to wait for the harvest.",
			"Earth", "Brown and Orange", "Benzoin", "Patience, Investment, Growth"}},
	{"Eight Of Pentacles",
		{"Sun in Virgo", "Yod",
			"Represents a time of hard work and dedication, a commitment to one's craft.", "Earth",
			"Blue and Green", "Vanilla", "Work, Skill, Diligence"}},
	{"Nine Of Pentacles",
		{"Venus in Virgo", "Yod",
			"Represents a time of financial independence, a life of luxury and refinement.",
			"Earth", "Purple and Green", "Jasmine", "Independence, Luxury, Self-Sufficiency"}},
	{"Ten Of Pentacles",
		{"Mercury in Virgo", "Yod",
			"Represents a time of family wealth and security, a legacy for future generations.",
			"Earth", "Green and Gold", "Rose", "Legacy, Family, Establishment"}},
	{"Page Of Pentacles",
		{"Earth of Earth", "Heh",
			"Represents a message of financial opportunity, a new job or investment.", "Earth",
			"Green and Brown", "Patchouli", "Opportunity, Manifestation, Learning"}},
	{"Knight Of Pentacles",
		{"Air of Earth", "Heh",
			"Represents a practical and reliable young man, a hard worker with a strong sense of "
			"duty.",
			"Earth", "Brown and Green", "Cypress", "Reliability, Routine, Patience"}},
	{"Queen Of Pentacles",
		{"Water of Earth", "Heh",
			"Represents a nurturing and practical woman, a successful businesswoman and a loving "
			"mother.",
			"Earth", "Green and Brown", "Rose", "Practicality, Nurturing, Abundance"}},
	{"King Of Pentacles",
		{"Fire of Earth", "Heh",
			"Represents a wealthy and successful man, a generous and responsible leader.", "Earth",
			"Green and Gold", "Sandalwood", "Prosperity, Leadership, Security"}},
	{"Ace Of Swords",
		{"Air", "Vav",
			"Represents the beginning of a new intellectual cycle, the potential for clarity and "
			"truth.",
			"Air", "White and Blue", "Frankincense", "Clarity, Truth, Intellect"}},
	{"Two Of Swords",
		{"Moon in Libra", "Lamed",
			"Represents a time of indecision, a need to make a difficult choice.", "Air",
			"Blue and Gray", "Myrrh", "Indecision, Truce, Stalemate"}},
	{"Three Of Swords",
		{"Saturn in Libra", "Lamed",
			"Represents a time of heartbreak and sorrow, a painful but necessary separation.",
			"Air", "Blue and Red", "Patchouli", "Heartbreak, Separation, Sorrow"}},
	{"Four Of Swords",
		{"Jupiter in Libra", "Lamed",
			"Represents a time of rest and recuperation, a need to withdraw from the world.", "Air",
			"Blue and White", "Copal", "Rest, Restoration, Contemplation"}},
	{"Five Of Swords",
		{"Venus in Aquarius", "Tzaddi",
			"Represents a time of conflict and defeat, a need to surrender and move on.", "Air",
			"Blue and Black", "Turpentine", "Conflict, Defeat, Shame"}},
	{"Six Of Swords",
		{"Mercury in Aquarius", "Tzaddi",
			"Represents a time of transition and change, a journey to a better place.", "Air",
			"Blue and Gray", "Benzoin", "Transition, Travel, Movement"}},
	{"Seven Of Swords",
		{"Moon in Aquarius", "Tzaddi",
			"Represents a time of deception and betrayal, a need to be cautious and alert.", "Air",
			"Gray and Blue", "Night-Blooming Jasmine", "Deception, Strategy, Avoidance"}},
	{"Eight Of Swords",
		{"Jupiter in Gemini", "Zain",
			"Represents a time of restriction and confinement, a need to break free from "
			"self-imposed limitations.",
			"Air", "Blue and Black", "Wintergreen", "Restriction, Entrapment, Powerlessness"}},
	{"Nine Of Swords",
		{"Mars in Gemini", "Zain",
			"Represents a time of anxiety and despair, a need to face one's fears.", "Air",
			"Black and Red", "Night-Blooming Jasmine", "Anxiety, Fear, Despair"}},
	{"Ten Of Swords",
		{"Sun in Gemini", "Zain",
			"Represents a time of complete and utter ruin, the end of a difficult cycle.", "Air",
			"Black and Gray", "Asafoetida", "Ruins, Failure, Endings"}},
	{"Page Of Swords",
		{"Earth of Air", "Vav",
			"Represents a message of conflict and challenge, a need to be assertive and stand up "
			"for oneself.",
			"Air", "Blue and Yellow", "Lavender", "Curiosity, Vigilance, Message"}},
	{"Knight Of Swords",
		{"Air of Air", "Vav",
			"Represents a young man who is intelligent and ambitious, but also reckless and "
			"impulsive.",
			"Air", "Blue and Red", "Peppermint", "Action, Impulsiveness, Defense"}},
	{"Queen Of Swords",
		{"Water of Air", "Vav",
			"Represents a woman who is intelligent and independent, but also cold and aloof.",
			"Air", "Blue and White", "Chamomile", "Independent, Perceptive, Clear-minded"}},
	{"King Of Swords",
		{"Fire of Air", "Vav",
			"Represents a man who is intelligent and authoritative, but also ruthless and "
			"judgmental.",
			"Air", "Blue and Purple", "Frankincense", "Power, Authority, Clarity"}},
	{"Ace Of Wands",
		{"Fire", "Yod",
			"Represents the beginning of a new creative cycle, the potential for growth and "
			"expansion.",
			"Fire", "Red and Gold", "Sandalwood", "Creativity, Passion, Potential"}},
	{"Two Of Wands",
		{"Mars in Aries", "Heh",
			"Represents a time of planning and preparation, a need to make a choice between two "
			"paths.",
			"Fire", "Red and Blue", "Cinnamon", "Planning, Decision, Dominion"}},
	{"Three Of Wands",
		{"Sun in Aries", "Heh",
			"Represents a time of exploration and discovery, a need to expand one's horizons.",
			"Fire", "Red and Purple", "Vanilla", "Exploration, Expansion, Discovery"}},
	{"Four Of Wands",
		{"Venus in Aries", "Heh",
			"Represents a time of celebration and joy, a happy and harmonious home life.", "Fire",
			"Red and Green", "Rose", "Celebration, Harmony, Home"}},
	{"Five Of Wands",
		{"Saturn in Leo", "Teth",
			"Represents a time of competition and conflict, a need to prove oneself.", "Fire",
			"Yellow and Red", "Peppermint", "Competition, Conflict, Rivalry"}},
	{"Six Of Wands",
		{"Jupiter in Leo", "Teth",
			"Represents a time of victory and success, a public recognition of one's "
			"achievements.",
			"Fire", "Red and Blue", "Star Anise", "Victory, Recognition, Success"}},
	{"Seven Of Wands",
		{"Mars in Leo", "Teth",
			"Represents a time of courage and defiance, a need to stand up for one's beliefs.",
			"Fire", "Red and Purple", "Cinnamon", "Challenge, Bravery, Determination"}},
	{"Eight Of Wands",
		{"Mercury in Sagittarius", "Samekh",
			"Represents a time of rapid progress and communication, a sudden burst of energy.",
			"Fire", "Yellow and Blue", "Peppermint", "Speed, Communication, Swiftness"}},
	{"Nine Of Wands",
		{"Moon in Sagittarius", "Samekh",
			"Represents a time of strength and resilience, a need to persevere in the face of "
			"adversity.",
			"Fire", "Red and Brown", "Cypress", "Resilience, Courage, Persistence"}},
	{"Ten Of Wands",
		{"Saturn in Sagittarius", "Samekh",
			"Represents a time of burden and responsibility, a need to delegate and ask for "
			"help.",
			"Fire", "Red and Black", "Wintergreen", "Burden, Responsibility, Completion"}},
	{"Page Of Wands",
		{"Earth of Fire", "Yod",
			"Represents a message of creative inspiration, a new project or idea.", "Fire",
			"Red and Yellow", "Sandalwood", "Enthusiasm, Exploration, Message"}},
	{"Knight Of Wands",
		{"Air of Fire", "Yod",
			"Represents a young man who is energetic and adventurous, but also reckless and "
			"impulsive.",
			"Fire", "Red and Orange", "Cinnamon", "Energy, Adventure, Impulsiveness"}},
	{"Queen Of Wands",
		{"Water of Fire", "Yod",
			"Represents a woman who is confident and charismatic, but also hot-tempered and "
			"demanding.",
			"Fire", "Red and Orange", "Cinnamon", "Confidence, Passion, Determination"}},
	{"King Of Wands",
		{"Fire of Fire", "Yod",
			"Represents a man who is a natural leader, a visionary with a passion for life.",
			"Fire", "Red and Purple", "Sandalwood", "Leadership, Vision, Charisma"}}};


Reading::Reading(const std::vector<BString>& cardNames)
	:
	fCardNames(cardNames)
{
}


BString
Reading::GetInterpretation()
{
	return GenerateInterpretation();
}


BString
Reading::GenerateInterpretation()
{
	BString interpretation = "";
	for (const BString& cardName : fCardNames) {
		if (cardData.count(cardName) > 0) {
			interpretation << "Card: " << cardName << "\n";
			interpretation << "Astrological Sign: " << cardData[cardName].astrological << "\n";
			interpretation << "Hebrew Letter: " << cardData[cardName].hebrewLetter << "\n";
			interpretation << "Element: " << cardData[cardName].element << "\n";
			interpretation << "Color: " << cardData[cardName].color << "\n";
			interpretation << "Incense: " << cardData[cardName].incense << "\n";
			interpretation << "Keywords: " << cardData[cardName].keywords << "\n";
			interpretation << "Meaning: " << cardData[cardName].meaning << "\n\n";
		}
	}
	return interpretation;
}
